/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;

/**
 * @author Usuario
 */
public class login_old extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public login_old() {

        Image icon = new ImageIcon(Objects.requireNonNull(getClass().getResource("..\\images\\logo_escudo.png"))).getImage();
        setTitle("AtiLoMan");
        setIconImage(icon);
        initComponents();
        setLocationRelativeTo(null); //Centrar en la pantalla

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new JPanel();
        jPanel4 = new JPanel();
        jlbExit = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel9 = new JLabel();
        jLabel4 = new JLabel();
        jlbConfig = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        txtUsuario = new JTextField();
        txtContrasena = new JPasswordField();
        jButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new Color(0, 51, 51));

        jlbExit.setIcon(new ImageIcon(getClass().getResource("/images/x.png"))); // NOI18N
        jlbExit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbExitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new Color(33, 150, 243));
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");

        jLabel3.setFont(new Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("AtiLoMan System");

        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel9.setIcon(new ImageIcon(getClass().getResource("/images/logo_escudo.png"))); // NOI18N

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlbExit)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlbExit)
                .addGap(225, 225, 225)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(159, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 420));

        jLabel4.setFont(new Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(SwingConstants.LEFT);
        jLabel4.setText("Entrar en AtiLoMan System");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 310, -1));

        jlbConfig.setForeground(new Color(33, 150, 243));
        jlbConfig.setHorizontalAlignment(SwingConstants.RIGHT);
        jlbConfig.setText("Configuración de la DB");
        jlbConfig.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlbConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbConfigMouseClicked(evt);
            }
        });
        jPanel3.add(jlbConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 150, -1));

        jLabel6.setFont(new Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel6.setForeground(new Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(SwingConstants.LEFT);
        jLabel6.setText("Acceso a Usuarios");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 180, -1));

        jLabel7.setFont(new Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(SwingConstants.LEFT);
        jLabel7.setText("Usuario ID:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 180, -1));

        jLabel8.setFont(new Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(SwingConstants.LEFT);
        jLabel8.setText("Contraseña:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 180, -1));

        txtUsuario.setToolTipText("Introduce tu Usuario");
        txtUsuario.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 198, 340, 25));

        txtContrasena.setToolTipText("Introduce tu Contraseña");
        txtContrasena.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        jPanel3.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 340, 25));

        jButton1.setBackground(new Color(0, 122, 255));
        jButton1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 80, 30));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


        String usuario = txtUsuario.getText();
        String contrasena = new String(txtContrasena.getPassword());
        boolean credencialesValidas = checkCredenciales(usuario, contrasena);
        if (credencialesValidas) {
            //JOptionPane.showMessageDialog(this, "Bienvenido " + usuario + "!");

            // Abrimos una nueva ventana
            principal principal = new principal();
            principal.setVisible(true);
            // Cierra la ventana de inicio de sesión
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean checkCredenciales(String usuario, String contrasena) {
        // aqui puedes comprobar las credenciales contra una base de datos o un archivo de texto
        // por ejemplo
        if (usuario.equals("admin") && contrasena.equals("1234")) {
            return true;
        }
        return false;
    }

    private void jlbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlbExitMouseClicked

    private void jlbConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbConfigMouseClicked
        // TODO add your handling code here:
        Image icon = new ImageIcon(Objects.requireNonNull(getClass().getResource("..\\images\\logo_escudo.png"))).getImage();

        frmDB internalFrame = new frmDB();
        JDesktopPane desktop = new JDesktopPane();
        desktop.add(internalFrame, BorderLayout.CENTER);

        JFrame mainFrame = new JFrame();
        mainFrame.setContentPane(desktop);
        mainFrame.setSize(500, 400);
        mainFrame.setIconImage(icon);
        mainFrame.setResizable(false);
        mainFrame.setExtendedState(JFrame.NORMAL);

        mainFrame.setLocationRelativeTo(null); //Centrar en la pantalla
        mainFrame.setVisible(true);

// Para mostrar el JInternalFrame
        internalFrame.setVisible(true);
        internalFrame.setLocation((desktop.getWidth() - internalFrame.getWidth()) / 2, (desktop.getHeight() - internalFrame.getHeight()) / 2);





    }//GEN-LAST:event_jlbConfigMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_old().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JLabel jlbConfig;
    private JLabel jlbExit;
    private JPasswordField txtContrasena;
    private JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
